### ISSUE TITLE
[Browser Compat] Card group doesn't look quite right in IE11

### ISSUE THREAD

**Issue by AdamTReineke** [cjcenizal/flexbox-patterns#1]
![card-group](https://cloud.githubusercontent.com/assets/518655/14684254/fa93e80c-06e3-11e6-961f-f199eb65f355.PNG)

While everyone should test their sites in the browsers they care about, especially for a new feature like Flexbox, it's probably worth adding a note that this doesn't work in IE 11.

I didn't try to reduce the issue or work around it to see what the root cause is.

**Comment by kris4de** [comment]
IE 11 has some bugs concerning flexbox: http://caniuse.com/#search=flexbox

I think that these tips are great for beginners. But the really challenging stuff are workarounds for browser compat.

**Comment by cjcenizal** [comment]
Thanks @AdamTReineke! I was able to reproduce and I'm working on solving this now.  Good points @kris4de.

**Comment by cjcenizal** [comment]
Got it. This is a manifestation of this bug: https://github.com/philipwalton/flexbugs#4-flex-shorthand-declarations-with-unitless-flex-basis-values-are-ignored

I'll solve this by setting flex-basis to `0%` instead of `0`.

**Comment by cjcenizal** [comment]
Fixed in https://github.com/cjcenizal/flexbox-patterns/releases/tag/0.1.2
