### ISSUE TITLE
defaults of flex-grow and flex-shrink are wrong

### ISSUE THREAD

**Issue by teppeis** [cjcenizal/flexbox-patterns#8]
> - flex-grow: 1 indicates how the element expands as its container gets larger. By default, the value is 1. We’ll set it to 1 so that the card will expand as much as possible to fill the container.
> - flex-shrink: 1 controls how the element shrinks as its container gets smaller. By default, this value is 0. When we set it to 1, we tell the card to shrink as much as it has to, to fit into its container.
>
> http://www.flexboxpatterns.com/card-group

In correct:
- flex-grow: 0 https://developer.mozilla.org/en-US/docs/Web/CSS/flex-grow
- flex-shrink: 1 https://developer.mozilla.org/en-US/docs/Web/CSS/flex-shrink

The following source code comment is correct.

**Comment by cjcenizal** [comment]
Thanks @teppeis ! I just pushed the fix.

**Comment by teppeis** [comment]
@cjcenizal Thanks for awesome site!
